@startuml
'https://plantuml.com/class-diagram

class Main{
    +static void main(String[] args)
}



class MainMenu {
    -String userFilePath;
    -String movieFilePath;
    -String seriesFilePath;
    + MainMenu(String userFilePath, String movieFilePath, String seriesFilePath);
    -ArrayList<Movie> movieList;
    -ArrayList<Series> seriesList;
    -ArrayList<User> users;
    -User currentUser;
    -UIText ui;

    +void show();
    +void login();
    +void createAccount();
    +void loadUsersFromFile();
    +void saveUsersToFile();
    +void showUserMenu();
}

class UIText {
        Scanner scanner;
        +void displayMsg(String msg);
        +int promptNumeric(String msg);
        +String promptText(String msg);
        +boolean promptBinary(String msg);
}

class FileIO {
    +ArrayList<User> loadUsers(String filepath);
    +void saveUsers(String filepath, ArrayList<User> users);
    +ArrayList<Medie> loadMovies(String filepath, GenreManager gm);
    +ArrayList<Medie> loadSeries(String filepath, GenreManager gm);
    +void saveUserLists(String folderPath, User user);
    +void loadUserLists(String folderPath, User user, ArrayList<Medie> allMedia);
}

interface MediePlay {
    +void medieIsPlaying();
}

interface MediePause {
    +void medieIsPaused();
}

interface MedieEnd {
    +void medieIsEnded();
}

abstract class Medie {
    -String title;
    -ArrayList<Genre> genres;
    -int releaseYear;
    -double rating;
    -ArrayList<User> usersWhoHaveSeen;

    +Medie(String title, ArrayList<Genre> genres, int releaseYear, double rating);
    +String getTitle();
    +ArrayList<Genre> getGenres();
    +int getReleaseYear();
    +void setRating(double rating);
    +boolean matchesGenre(String genre);
    +boolean matchesTitle(String title);
    +void displayInfo();
    +String toFileString();
    +void medieIsPlaying();
    +void medieIsPaused();
    +void medieIsEnded();
}
class Movie {
    -double movieLength;

    +Movie(String title, ArrayList<Genre> genres, int releaseYear, double rating, double movieLength);
    +int getMovieLength();
    +void setMovieLength(double length);
    +boolean isLongMovie();
    +boolean isShortMovie();
    +boolean isRatedAbove(double isRating);
}

class Series {
    -int seasons;
    -int episodes;
    -double episodeLength;
    +Series(String title, ArrayList<Genre> genres, int releaseYear, double rating, int seasons, int episodes, int episodeLength);
    +int getSeasons();
    +int getEpisodes();
    +int getEpisodeLength();
    +void setSeasons(int seasons);
    +void setEpisodes(int episodes);
    +void setEpisodeLength(int length);
    +boolean isMiniSeries();
    +boolean isRatedAbove(double isRating);
}

class User {
    -String name;
    -String mail;
    -String code;
    -ArrayList<Medie> seenList;
    -ArrayList<Medie> favoriteList;
    -ArrayList<Medie> continueList;
    +User(String name, String mail, String code);
    +String getName();
    +String getMail();
    +String getCode();
    +void addToList(String listName, Medie media);
    +void removeFromList(String listName, Medie media);
    +void viewList(String listName);
}

class Genre {
    -String genreName;
    -String genreDescription;
    +Genre(String genreName, String genreDescription);
    +String getName();
    +String getDescription();
    +void setDescription(String description);
    +String toString();
}

class GenreManager {
    -ArrayList<Genre> genreList;
    +GenreManager(ArrayList<Genre> genreList);
    +void addGenre(Genre genre);
    +ArrayList<Genre> getAllGenres();
    +Genre getGenreByName(String name);
    +void printGenres();
}

' IS-A relationships
Medie <|-- Movie
Medie <|-- Series

Medie ..|> MediePlay
Medie ..|> MediePause
Medie ..|> MedieEnd





' HAS-A relationships
MainMenu o-- User
MainMenu o-- UIText
MainMenu o-- Movie
MainMenu o-- Series
MainMenu o-- GenreManager

User o-- Medie
Medie *-- Genre
Medie o-- User

GenreManager *-- Genre

FileIO --> Medie
Main o-- MainMenu



@enduml